version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - '@adevinta/spark-dev'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@storybook/*'
      - dependency-name: 'storybook'
    commit-message:
      prefix: 'build(npm)'
