name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Cancel Previous Redundant Builds
  check-skip:
    runs-on: ubuntu-latest
    name: Check redundant workflows
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  # Assigns the event creator to the PR
  assign_pr_owner:
    runs-on: ubuntu-latest
    name: PR assignment
    steps:
      - name: Assign PR to creator
        uses: toshimaru/auto-author-assign@v1.6.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  contributions:
    runs-on: ubuntu-latest
    name: Contributions
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        with:
          image_size: 32
          readme_path: 'README.md'
          columns_per_row: 20
          commit_message: 'docs(chore): update contributions'
          committer_username: 'spark-ui-bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
